adding the Contact page
alissatroiano/team-11 pull request #41
Opened 2023-05-12 18:07 UTC by Jawahir01

# Death Scarper | Death Snare | Darth Escape | Escape the Death Star | Death Star Escape | Death Star Experience

## Description

## Breaking Changes
 
## Issue
- ***Add linked issue here (type #   )***

## Screenshots (if appropriate)

2023-05-12 18:26 UTC, Shane-Donlon requested changes
rename of container, column, card classes to .contacts-page__container .contacts-page__column .contacts-page__card 

these are all common class names in CSS . Thanks :)

2023-05-12 18:54 UTC, Shane-Donlon approved these changes

2023-05-12 18:56 UTC, Shane-Donlon requested changes
container card column row classes to be changed

2023-05-14 22:41 UTC, alissatroiano approved these changes

2023-05-14 22:41 UTC, merged